export const GET_BLOG_BY_QR = "GET_BLOG_BY_QR";
export const GET_BLOG_BY_QR_SUCCESS = "GET_BLOG_BY_QR_SUCCESS";
export const GET_BLOG_BY_QR_ERROR = "GET_BLOG_BY_QR_ERROR";

export const GET_BLOG_BY_UNIQUE_KEY = "GET_BLOG_BY_UNIQUE_KEY";
export const GET_BLOG_BY_UNIQUE_KEY_SUCCESS = "GET_BLOG_BY_UNIQUE_KEY_SUCCESS";
export const GET_BLOG_BY_UNIQUE_KEY_ERROR = "GET_BLOG_BY_UNIQUE_KEY_ERROR";

export const GET_BLOG_DETAIL_BY_QR_KEY = "GET_BLOG_DETAIL_BY_QR_KEY";
export const GET_BLOG_DETAIL_BY_QR_KEY_SUCCESS =
  "GET_BLOG_DETAIL_BY_QR_KEY_SUCCESS";
export const GET_BLOG_DETAIL_BY_QR_KEY_ERROR =
  "GET_BLOG_DETAIL_BY_QR_KEY_ERROR";

export const SAVE_BLOG_IN_HISTORY = "SAVE_BLOG_IN_HISTORY";

export const SCAN_QR = "SCAN_QR";
export const SCAN_QR_SUCCESS = "SCAN_QR_SUCCESS";
export const SCAN_QR_ERROR = "SCAN_QR_ERROR";

export const GET_ALL_LIST_BLOG = "GET_ALL_LIST_BLOG";
export const GET_ALL_LIST_BLOG_SUCCESS = "GET_ALL_LIST_BLOG_SUCCESS";
export const GET_ALL_LIST_BLOG_ERROR = "GET_ALL_LIST_BLOG_ERROR";
